### PR TITLE
fix: arrow parsing for nested and nullable fields

### LINKED ISSUE #518: ReadClient throws on null values
https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L146 this can be `null` and `null` is an object, which causes nullable fields to throw. For example in this case:

```
fieldData.toString();
>>> {"column_name": null}
```

Then it gets passed to https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L159 and enter the object path because `typeof null === 'object'` is `true` then break on `Object.keys(null)` in https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L168

> TypeError: Cannot convert undefined or null to object

### PR DESCRIPTION
**Pull request by alvarowolfx**
Improves parsing of arrow records to TableRow format by increasing test coverage and checking arrow data types.

Fixes  #518 🦕

### CODE REVIEW

File: src/reader/arrow_transform.ts [hunk 1]
```diff
@@ -156,21 +157,33 @@ export class ArrowRecordBatchTableRowTransform extends Transform {
...
-    if (fieldValue instanceof Vector) {
-      const arr = fieldValue.toJSON();
-      return arr.map((v: any) => {
-        return {v: convertArrowValue(v)};
-      });
-    }
-    const tableRow: TableRow = {f: []};
+function convertArrowValue(fieldValue: any, type: DataType): any {
+  if (fieldValue === null) {
+    return null;
```
Comment (leahecole) [inline src/reader/arrow_transform.ts:162]: Do we also need to care about it being undefined?

File: src/reader/arrow_transform.ts [hunk 2]
```diff
@@ -156,21 +157,33 @@ export class ArrowRecordBatchTableRowTransform extends Transform {
...
+  }
+  if (DataType.isList(type)) {
+    const arr = fieldValue.toJSON();
+    return arr.map((v: any) => {
+      return {v: convertArrowValue(v, type.children[0].type)};
```
Comment (leahecole) [inline src/reader/arrow_transform.ts:167]: Why do we only care about `type.children[0]`?

File: system-test/reader_client_test.ts [hunk 3]
```diff
@@ -97,9 +124,26 @@ describe('reader.ReaderClient', () => {
...
-        {name: 'Alan Turing', row_num: 2},
-        {name: 'Bell', row_num: 3},
+        {
+          name: 'Ada Lovelace',
+          row_num: 1,
+          optional: 'Some data',
+          list: [1],
+          metadata: {
+            created_at: bigquery.timestamp('2020-04-27T18:07:25.356Z'),
+            updated_at: bigquery.timestamp('2020-04-27T18:07:25.356Z'),
```
Comment (leahecole) [inline system-test/reader_client_test.ts:134]: Would it be a more robust test for the update timestamp to be different than the create one? Or does it not really matter in this particular case?

**Review by leahecole — CHANGES_REQUESTED** [review]
mostly questions! Probably just needs a few comments for other maintainers who might not be as familiar with arrow

File: src/reader/arrow_transform.ts (hunk 1 above)
Comment (alvarowolfx) [reply src/reader/arrow_transform.ts:162]: that value is coming from the BigQuery backend, so undefined is not a possible value in that scenario.

File: src/reader/arrow_transform.ts (hunk 2 above)
Comment (alvarowolfx) [reply src/reader/arrow_transform.ts:167]: Arrays/lists on BigQuery have the same datatype for every element, so getting the first one is enough here.

File: src/reader/arrow_transform.ts [hunk 4]
```diff
@@ -156,21 +157,34 @@ export class ArrowRecordBatchTableRowTransform extends Transform {
...
-    }
-    const tableRow: TableRow = {f: []};
+function convertArrowValue(fieldValue: any, type: DataType): any {
+  if (fieldValue === null) {
+    return null;
+  }
+  if (DataType.isList(type)) {
+    const arr = fieldValue.toJSON();
+    return arr.map((v: any) => {
+      const elemType = type.children[0].type;
```
Comment (leahecole) [inline src/reader/arrow_transform.ts:167]:
```suggestion
      // Arrays/lists in BigQuery have the same datatype for every element
      // so getting the first one is all we need
      const elemType = type.children[0].type;
```

Comment (leahecole) [reply src/reader/arrow_transform.ts:167]: I used the GH UI so apoloiges if I break lint

File: system-test/reader_client_test.ts [hunk 5]
```diff
@@ -97,9 +124,26 @@ describe('reader.ReaderClient', () => {
...
-        {name: 'Alan Turing', row_num: 2},
-        {name: 'Bell', row_num: 3},
+        {
+          name: 'Ada Lovelace',
+          row_num: 1,
+          optional: 'Some data',
+          list: [1],
+          metadata: {
+            created_at: bigquery.timestamp('2020-04-27T18:07:25.356Z'),
+            updated_at: bigquery.timestamp('2020-04-27T20:07:25.356Z'),
```
Comment (leahecole) [inline system-test/reader_client_test.ts:134]:
```suggestion
            updated_at: bigquery.timestamp('2020-04-27T20:07:35.356Z'),
```

Comment (leahecole) [reply system-test/reader_client_test.ts:134]: even if it doesn't change things, let's add 10 min for posterity 😁

**Review by leahecole — APPROVED** [review]
I added two suggestions but otherwise lgtm

File: system-test/reader_client_test.ts (hunk 5 above)
Comment (alvarowolfx) [reply system-test/reader_client_test.ts:134]: I've already pushed a change that adds 2 hours
