### PR TITLE
fix: required table fields with value expression should be proto optional

### LINKED ISSUE #531: Can I specify CURRENT_TIMESTAMP for rows by Storage Write API?
### Please make sure you have searched for information in the following guides.

- [X] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
- [X] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
- [X] Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq
- [X] Check our libraries HOW-TO: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md
- [X] Check out our authentication guide: https://github.com/googleapis/google-auth-library-nodejs
- [X] Check out handwritten samples for many of our APIs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### Documentation Request

For example, for a query, we can insert `CURRENT_TIMESTAMP` as follows
```sql
INSERT INTO your_table_name (column1, column2, timestamp_column)
VALUES ('value1', 'value2', CURRENT_TIMESTAMP);
```

However, in the case of Storage Write API, passing the string `“CURRENT_TIMESTAMP”` to appendRows did not result in correct data.

Can I specify CURRENT_TIMESTAMP for rows by Storage Write API?

### PR DESCRIPTION
**Pull request by alvarowolfx**
When a BigQuery table column mode is set to `REQUIRED`, when converted to a protobuf label, it was being converted as `LABEL_REQUIRED`. This would make protobufjs encoding methods to set an empty value to it when converting to the wire format. But if the column has a `defaultValueExpression` and we want the backend to fill the data, we need to let the value stay `null | undefined`. 

This PR checks if there is a `defaultValueExpression` defined on the column and change the label to `LABEL_OPTIONAL` to let the backend fill the data.

Fixes #531 🦕

### CODE REVIEW

File: protos/protos.d.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2024 Google LLC
+// Copyright 2025 Google LLC
```
Comment (leahecole) [inline protos/protos.d.ts:1]:
```suggestion
// Copyright 2024 Google LLC
```
per ospo guidance the year should be the year the file was authored

File: protos/protos.js [hunk 2]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2024 Google LLC
+// Copyright 2025 Google LLC
```
Comment (leahecole) [inline protos/protos.js:1]:
```suggestion
// Copyright 2024 Google LLC
```

per ospo guidance the year should be the year the file was authored

**Review by leahecole — APPROVED** [review]
LGTM, but would like @shollyman to do a confidence check on this logic

**Review by shollyman — APPROVED** [review]
This is an interesting interaction with schema inference, given that the client side required-ness isn't strictly compatible with the default value feature.  Is it worth adding some more documentation to the adapt package to explain why this happens?
